import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
const inter = Inter({ subsets: ["latin"] });
import Header from "../components/header/header.jsx";
import Footer from "../components/footer/footer";
export default function Home() {
  return (
    <>
      <div className={styles.body}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        {/* <Header /> */}
        <main className={styles.main}></main>
        <Footer />
      </div>{" "}
    </>
  );
}
